[workspace]

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"

[dependencies]
borsh = "1.5.3"
solana-sdk = "~2.0"
spl-token = { version = "3", features = ["no-entrypoint"] }

[dependencies.trident-fuzz]
version = "0.11.1"

[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"
